const ActionTypes = {
    FETCH_LOCATIONS_BEGIN: "FETCH_LOCATIONS_BEGIN",
    FETCH_LOCATIONS_SUCCESS: "FETCH_LOCATIONS_SUCCESS",
    FETCH_LOCATIONS_ERROR: "FETCH_LOCATIONS_ERROR",
    FETCH_LOCATION_BEGIN: "FETCH_LOCATION_BEGIN",
    FETCH_LOCATION_SUCCESS: "FETCH_LOCATION_SUCCESS",
    FETCH_LOCATION_ERROR: "FETCH_LOCATION_ERROR"
}

export default ActionTypes;